on: push
name: cleans, build and test app (mobile - android)
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4 # Necessary to access local action
      
    - name: install dependencies
      uses: ./action
      with:
        args: pub get
        
    - name: clean stale build and cache
      uses: ./action
      with:
        args: clean

    - name: build apk
      uses: ./action
      with:
        args: build apk --release